MAP_WIDTH = 10
MAP_HEIGHT = 10
MOVE_TICK_RATE = 0.5   # Seconds per square movement
METAL_TICK_RATE = 1    # Seconds per metal gain
COMBAT_TICK_RATE = 1   # Seconds per combat tick
BUILD_TIME = 30        # Seconds to build colony
WINDOW_SIZE = (800, 600)  # Width x Height in pixels
TILE_SIZE = 60         # Pixels per tile (600x600 board)
FLASH_RATE = 0.5       # Seconds per flash toggle
